language: go
os: linux

go:
- 1.9

script:
- GOOS=darwin  GOARCH=amd64 go build -ldflags="-s -w" -o cpu-check-darwin
- GOOS=linux   GOARCH=amd64 go build -ldflags="-s -w" -o cpu-check-linux
- GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o cpu-check-windows.exe

after_success:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then openssl aes-256-cbc -K $encrypted_f10c94e8f9cb_key -iv $encrypted_f10c94e8f9cb_iv -in .travis.enc -out $HOME/.ssh/id_rsa -d; fi
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then chmod 400 $HOME/.ssh/id_rsa; fi
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then ssh -o StrictHostKeyChecking=no codeship@uniclust.mmseqs.com "mkdir -p /home/mirdita/repositories/mmseqs-webserver/util"; fi
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then scp -o StrictHostKeyChecking=no cpu-check-linux cpu-check-darwin cpu-check-windows.exe codeship@uniclust.mmseqs.com:/home/mirdita/repositories/mmseqs-webserver/util; fi