language: bash
os: osx

before_install:
  - brew update
  # workaround for GCC install issue, remove package that installed links to /usr/local/include/c++
  - brew cask list && brew cask uninstall --force oclint
  # coreutils and cmake dependencies are already pre-installed
  - brew install curl unzip make
  - brew upgrade node go wget git

script:
  - export GOPATH="${HOME}/go"
  - export PATH="${GOPATH}/bin:${PATH}"
  - go get -u github.com/kardianos/govendor
  - go get -u github.com/intel-go/cpuid
  - npm i
  - npm run electron:build
