language: bash
os: osx

before_install:
  - nvm unload
  - rm -rf ~/.nvm
  - brew update
  - brew cask list && brew cask uninstall --force oclint
  - brew install curl unzip make
  - brew upgrade node go wget git

script:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_d5229c4255f2_key -iv $encrypted_d5229c4255f2_iv -in certificate.p12.enc -out certificate.p12 -d; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then export CSC_LINK=./certificate.p12; fi
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then unset CSC_KEY_PASSWORD; unset GH_TOKEN; fi
  - export GOPATH="${HOME}/go"
  - export PATH="${GOPATH}/bin:${PATH}"
  - go get -u github.com/kardianos/govendor
  - go get -u github.com/intel-go/cpuid
  - npm i
  - npm run electron:build

env:
  global:
    - secure: bF6a48HKl2ZUjMPE4cIU92+g72ew2WLD5AgKK8E3TdbeU/KgSVUCRjZII5V4zDeAQDjcSIP/7h9tw42L8Xo58v6VMKe0fjgg4wMPM1Gwvwd8EJSa7Sh7YUh1Rk9Sd085xMyvN2artxc8lE2iiGZ64ti6W2BpNZp0kYH+byY72R8LGSzrTzSmpyU1aNYerwXhGxS4QoLlVwIqmb6ZxJyfYCSPt6r7d+1zJUy6Bl0xzawvQfR8u4gPq/qko0wDigheKaTg4uKcUZklSBIJZECrQckqxSGRqTarzNwBkyBbnBM+pOLtGMTVfjC6UjSL+8qiSuuQUW3NzwfJztryyeP3Gm3Tvo0fpatARgH/J7bdDarzMaCdWXOn3XW7E0Cy7Z7QEg469i0M9fI5d5VXEz/wLYNPCdhiXraGZ5fuVKW56epETSMEhjX7UkRaSJqtLfZSpGPYQEy92Pg5SEyu2xk97rM1Sy6qh1P7K51j/JZYVKGo112sD/vaUtBeFMH0fPnyXeRC7QotLzDmzqTO9Vl1b3uu0pLHH6O3GSjzc6STd2tVffA0RwVsvOTRm6C2RL8pjFqmkClR6JXD/hIjc3MyNHzQX7he7paOGZqLpIl9khG2dx/NWtEl7q++ctHJseg4sPwFVRvGkG4fF4sTQyVjLgi+xHnmiDVAXbKORUmyZCA=
    - secure: AiEZNzkkn5dwkmGRyoFDIpE1GU+sUPe5Vq0sVjjfiocgpD4c8psMcDiuM4YFmIS1RwBW64/+jDmuzYbVS4Tz5D8H2v5cP4lKNQBPJLtEooHv40+KkO09MhIws53O5G/GeSZsEU3/p0qhr4SAew+5k0L4VmwXk9a/Jeu4HybaexlNp76px4w1peUP4pSecigH35o+I3J3ypnCgnJHv14dCtqYaJQyGw9yMdLRM7r2CbRXItahE4c4BskGK04UJHjDTri5lcEJ5kpFhUYcqVA2wFMUeMk4BuKUUjVoXFNZsGy3Itqi4saEBdBxWLYrQyORjdGcG6M7eFnJ9WHeZSS3NeLZXEJCS88KJQRmXM9P6mD/tlQ6qNkHiOSt7p4lM55qtDUfvi8sBuHsJs8hjyd9sqIiPX00kCVXlS6ov0WV2oFxrjVd3YJ5uivZxW8JryzBHWcuvfb0Z6jRfd2AruszJXWaTXnTqoGELca0ou6t3NQyGrL6i2NHFSq0MbaO7RqlR0I9OSmWuV2cK+S77u54PVik3U0cW6lnktM6D8ag6vPYNkZR4d4ensVoUGybz8WTqcfnvFq9HAnemwX78aTlKcIBeOKW79ij23e9MVQ257e2momwD+LhgXqaD3bucqmKztXJoV9deGp2Z8nuIoHowHySapaAkfw78HWuKvTrvjg=
