# https://aka.ms/yaml

trigger:
  - master
pool:
  vmImage: 'macOS-10.14'
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
  - script: |
      npm install
      npm run electron:deps
      ELECTRON=1 node ./electron/build.js
  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: certificate.p12
      certPwd: $(CSC_KEY_PASSWORD)
  - task: CmdLine@2
    inputs:
      script: ./node_modules/.bin/electron-builder --x64 -mwl
    env:
      GH_TOKEN: $(GH_TOKEN)
