# https://aka.ms/yaml

trigger:
  - master
pool:
  vmImage: 'macOS-10.14'
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
  - script: |
      brew install unzip
      npm install
      npm run electron:deps
  - task: DownloadSecureFile@1
      inputs:
        secureFile: certificate.p12 
   - script:  npm run electron:build
     env:
       CSC_LINK: $(DOWNLOADSECUREFILE_SECUREFILEPATH)
       CSC_KEY_PASSWORD: $(CSC_KEY_PASSWORD)
       GH_TOKEN: $(GH_TOKEN)

