# https://aka.ms/yaml

trigger:
  tags:
    include:
    - v*
  branches:
    include:
    - master

pool:
  vmImage: 'macOS-10.14'
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
  - script: |
      npm install
      make all -j $(nproc --all)
      ELECTRON=1 node ./electron/build.js
  - task: DownloadSecureFile@1
    name: certificate
    inputs:
      secureFile: certificate.p12
  - task: CmdLine@2
    inputs:
      script: ./node_modules/.bin/electron-builder --x64 -mwl
    env:
      CSC_LINK: $(certificate.secureFilePath)
      CSC_KEY_PASSWORD: $(CSC_KEY_PASSWORD)
      GH_TOKEN: $(GH_TOKEN)
