version: '2'
services:
  mmseqs-web-redis:
    image: redis:alpine
    container_name: mmseqs-web-redis
    volumes:
      - redis-volume:/var/lib/redis

  mmseqs-web-api:
    container_name: mmseqs-web-api
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - mmseqs-web-redis
    volumes:
      - ./databases:/opt/mmseqs-web/databases
      - ./jobs:/opt/mmseqs-web/jobs

  mmseqs-web-worker:
    container_name: mmseqs-web-worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - mmseqs-web-redis
    volumes:
      - ./databases:/opt/mmseqs-web/databases:ro
      - ./jobs:/opt/mmseqs-web/jobs

  mmseqs-web-webserver:
    container_name: mmseqs-web-webserver
    build:
      context: .
      dockerfile: Dockerfile.web
    depends_on:
      - mmseqs-web-api
    volumes:
      - ./jobs:/opt/mmseqs-web/jobs:ro
    ports:
      - "80:80"

volumes:
  redis-volume: