version: '2'
services:
  mmseqs-web-redis:
    image: redis:alpine
    container_name: mmseqs-web-redis

  mmseqs-web-webserver:
    image: nginx:alpine
    container_name: mmseqs-web-webserver
    volumes:
      - ../dist:/var/www/mmseqs-web:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"

  mmseqs-web-php-fpm:
    build:
      context: ./php-fpm
    container_name: mmseqs-web-php-fpm
    volumes:
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini:ro
      - ../backend:/var/www/mmseqs-web
      - ../jobs:/var/mmseqs-web/jobs

  mmseqs-web-worker:
    build:
      context: ./worker
    container_name: mmseqs-web-worker
    volumes:
      - ../backend:/var/www/mmseqs-web:ro
      - ../jobs:/var/mmseqs-web/jobs
      - ../databases:/var/mmseqs-web/jobs
